name: swipe_to_apply_tr
description: "Türkiye İş Bulma - Swipe to Apply Job Search App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.6.2
  
  # Networking & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Local Storage
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.1
  
  # File Handling
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  open_file: ^3.5.10
  
  # PDF & Document Processing
  pdf: ^3.11.1
  printing: ^5.13.4
  syncfusion_flutter_pdf: ^28.1.33
  
  # Image Processing
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Swiping UI
  flutter_card_swiper: ^7.0.1
  
  # Authentication
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.1
  
  # Cloud Storage
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  
  # Notifications
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  
  # Web Scraping & Automation
  webview_flutter: ^4.10.0
  html: ^0.15.4
  beautiful_soup_dart: ^0.3.0
  
  # HTTP Client for scraping
  http: ^1.2.2
  
  # AI & ML
  dart_openai: ^5.1.0
  
  # Utils
  intl: 0.20.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.2
  
  # Gamification
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  
  # Security
  crypto: ^3.0.5
  encrypt: ^5.0.3
  
  # Turkish Language Support
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
